export type ConverterMeta = {
  slug: string;
  name: string;
  description: string;
  icon: string;
  category: string;
};

export const ALL_CONVERTERS: ConverterMeta[] = [
  // --- Construction ---
  { slug: "tile-calculator", name: "Tile Calculator", description: "Calculate the number of tiles needed for any floor or wall, plus waste.", icon: "Grid3X3", category: "Construction" },
  { slug: "paint-calculator", name: "Paint Calculator", description: "Calculate liters of paint needed for walls, accounting for doors and windows.", icon: "PaintBucket", category: "Construction" },
  { slug: "concrete-calculator", name: "Concrete Calculator", description: "Calculate cement, sand, and aggregate quantities for your concrete mix.", icon: "Layers", category: "Construction" },
  { slug: "brick-calculator", name: "Brick Calculator", description: "Calculate the number of bricks needed for a wall with mortar allowance.", icon: "Blocks", category: "Construction" },
  { slug: "square-footage-calculator", name: "Square Footage Calculator", description: "Calculate area in square feet and convert to other area units.", icon: "Ruler", category: "Construction" },
  { slug: "plot-area-calculator", name: "Plot Area Calculator (4-Sided)", description: "Calculate plot area from four sides (North, South, East, West) in Marla, Kanal, and Acres.", icon: "LandPlot", category: "Construction" },
  { slug: "room-area-calculator", name: "Room Area Calculator", description: "Calculate total area across multiple rooms and spaces.", icon: "Home", category: "Construction" },
  { slug: "wallpaper-calculator", name: "Wallpaper Calculator", description: "Calculate the number of wallpaper rolls needed for a room.", icon: "Palette", category: "Construction" },
  { slug: "flooring-calculator", name: "Flooring Calculator", description: "Calculate boxes of flooring needed and estimated cost.", icon: "LayoutGrid", category: "Construction" },
  { slug: "solar-panel-calculator", name: "Solar Panel Calculator", description: "Calculate panels needed, system cost, monthly generation, and payback period for a solar setup.", icon: "Sun", category: "Construction" },
  { slug: "roofing-calculator", name: "Roofing Calculator", description: "Calculate roof surface area, shingle bundles, and squares for gable, hip, or shed roofs.", icon: "Home", category: "Construction" },
  { slug: "stair-calculator", name: "Stair Calculator", description: "Plan stair risers, treads, total run, and stringer length with IRC code compliance check.", icon: "Stamp", category: "Construction" },
  { slug: "fence-calculator", name: "Fence Calculator", description: "Estimate posts, panels, rails, and concrete bags for a fence.", icon: "FenceIcon", category: "Construction" },
  { slug: "lumber-board-feet-calculator", name: "Lumber Board Feet Calculator", description: "Calculate board feet for one or many lumber sizes with cost-per-board-foot estimate.", icon: "TreePine", category: "Construction" },
  { slug: "drywall-calculator", name: "Drywall Calculator", description: "Calculate drywall sheets, joint compound, tape, and screws for a room.", icon: "LayoutGrid", category: "Construction" },
  { slug: "gravel-sand-calculator", name: "Gravel, Sand & Aggregate Calculator", description: "Calculate volume in cubic yards/metres and weight in tonnes for gravel, sand, topsoil, and mulch.", icon: "Layers", category: "Construction" },
  { slug: "hvac-btu-calculator", name: "HVAC BTU Sizing Calculator", description: "Estimate cooling and heating BTU/hr for any room with climate, sun, insulation adjustments.", icon: "Wind", category: "Construction" },

  // --- Date & Time ---
  { slug: "age-calculator", name: "Age Calculator", description: "Calculate exact age in years, months, and days from date of birth.", icon: "Calendar", category: "Date & Time" },
  { slug: "date-difference-calculator", name: "Date Difference Calculator", description: "Calculate the exact difference between any two dates in multiple units.", icon: "CalendarClock", category: "Date & Time" },
  { slug: "working-days-calculator", name: "Working Days Calculator", description: "Count working days (Mon-Fri) between two dates, excluding weekends.", icon: "Timer", category: "Date & Time" },
  { slug: "countdown-timer", name: "Countdown Timer", description: "Live countdown in days, hours, minutes, and seconds to any future date.", icon: "Timer", category: "Date & Time" },
  { slug: "add-subtract-days-calculator", name: "Add / Subtract Days Calculator", description: "Add or subtract days, weeks, months, or years from any date.", icon: "CalendarPlus", category: "Date & Time" },
  { slug: "time-duration-calculator", name: "Time Duration Calculator", description: "Calculate the duration between two times in hours and minutes.", icon: "Clock", category: "Date & Time" },
  { slug: "time-zone-converter", name: "Time Zone Converter", description: "Convert time between any two cities or time zones worldwide.", icon: "Globe", category: "Date & Time" },
  { slug: "salah-times-calculator", name: "Salah Times Calculator", description: "Daily prayer times (Fajr, Dhuhr, Asr, Maghrib, Isha) with countdown to next prayer.", icon: "Sunrise", category: "Islamic" },
  { slug: "hijri-gregorian-converter", name: "Hijri ↔ Gregorian Date Converter", description: "Convert dates between the Islamic Hijri (lunar) and Gregorian (solar) calendars.", icon: "Star", category: "Islamic" },
  { slug: "pomodoro-timer", name: "Pomodoro Timer", description: "Focus timer with 25-min work sessions, 5-min breaks, and a long break every 4 cycles.", icon: "Brain", category: "Date & Time" },
  { slug: "world-clock", name: "World Clock & Meeting Planner", description: "Side-by-side clocks for cities worldwide with live work-hours indicators.", icon: "Globe", category: "Date & Time" },
  { slug: "sehri-iftar-schedule-calculator", name: "Sehri & Iftar Ramadan Schedule", description: "Generate a printable 30-day Ramadan calendar with Sehri, Fajr, Sunrise, Iftar, and Isha times.", icon: "Moon", category: "Islamic" },
  { slug: "hijri-date-today", name: "Hijri Date Today", description: "Live Hijri date widget with weekday, sacred-month status, and countdowns to Ramadan and Eid.", icon: "MoonStar", category: "Islamic" },

  // --- Financial ---
  { slug: "loan-emi-calculator", name: "Loan / EMI Calculator", description: "Estimate your monthly loan payments, total interest, and repayment schedule.", icon: "Landmark", category: "Financial" },
  { slug: "percentage-calculator", name: "Percentage Calculator", description: "Calculate percentages for discounts, tax, tips, profit margins, and more.", icon: "Percent", category: "Financial" },
  { slug: "zakat-calculator", name: "Zakat Calculator", description: "Calculate your annual Zakat obligation based on Nisab and your net zakatable wealth.", icon: "Coins", category: "Islamic" },
  { slug: "income-tax-calculator-pakistan", name: "Income Tax Calculator (Pakistan)", description: "Calculate annual and monthly income tax in Pakistan based on FBR 2024-25 slabs.", icon: "Receipt", category: "Financial" },
  { slug: "gst-calculator", name: "GST / Sales Tax Calculator", description: "Add or remove GST/sales tax from any amount, with Pakistan's 17% preset.", icon: "Calculator", category: "Financial" },
  { slug: "tip-calculator", name: "Tip Calculator", description: "Calculate tips, split bills between people, and compute per-person totals.", icon: "Wallet", category: "Financial" },
  { slug: "salary-calculator", name: "Advanced Salary Calculator", description: "Convert, estimate take-home, calculate overtime, analyze raises, and compare job offers.", icon: "Wallet", category: "Financial" },
  { slug: "discount-calculator", name: "Discount Calculator", description: "Calculate sale price, total savings, and final price after a percentage discount.", icon: "Tag", category: "Financial" },
  { slug: "profit-margin-calculator", name: "Profit Margin Calculator", description: "Calculate profit, margin %, and markup % from cost and selling price.", icon: "TrendingUp", category: "Financial" },
  { slug: "markup-calculator", name: "Markup Calculator", description: "Calculate selling price from cost and a desired markup percentage.", icon: "TrendingUp", category: "Financial" },
  { slug: "break-even-calculator", name: "Break-even Calculator", description: "Find the units and revenue needed to cover your fixed and variable costs.", icon: "Scale", category: "Financial" },
  { slug: "cost-per-unit-calculator", name: "Cost Per Unit Calculator", description: "Compare the per-unit price of two product sizes to find the better deal.", icon: "ShoppingCart", category: "Financial" },
  { slug: "compound-interest-calculator", name: "Compound Interest Calculator", description: "Calculate future value with compound interest, periodic contributions, and growth charts.", icon: "PiggyBank", category: "Financial" },
  { slug: "faraiz-inheritance-calculator", name: "Faraiz (Islamic Inheritance) Calculator", description: "Calculate Islamic inheritance shares per Quran 4:11, 4:12, and 4:176.", icon: "Users", category: "Islamic" },
  { slug: "qurbani-cost-calculator", name: "Qurbani Cost Estimator", description: "Estimate the per-share cost of a Qurbani animal including butcher, transport, and meat distribution.", icon: "Beef", category: "Islamic" },
  { slug: "mahr-calculator", name: "Mahr Calculator", description: "Calculate Islamic Mahr (dower) — Mahr-e-Fatimi, custom amount, or split into prompt and deferred.", icon: "Heart", category: "Islamic" },
  { slug: "vehicle-token-tax-pk-calculator", name: "Vehicle Token Tax (Pakistan)", description: "Estimate annual vehicle token tax for all provinces including FBR Section 234 advance income tax.", icon: "Car", category: "Financial" },
  { slug: "property-registration-tax-pk-calculator", name: "Property Registration Tax (Pakistan)", description: "Buyer + seller property registration cost — stamp duty, transfer fee, CVT, and FBR WHT.", icon: "Building", category: "Financial" },

  // --- Fun ---
  { slug: "age-on-planets-calculator", name: "Age on Other Planets", description: "See how old you'd be on Mercury, Mars, Jupiter, and other planets.", icon: "Rocket", category: "Fun" },
  { slug: "chronological-age-calculator", name: "Chronological Age Calculator", description: "Calculate someone's age on any past or future date.", icon: "CalendarHeart", category: "Fun" },
  { slug: "zodiac-sign-calculator", name: "Zodiac Sign Calculator", description: "Find your Western and Chinese zodiac signs from your date of birth.", icon: "Stars", category: "Fun" },
  { slug: "days-until-calculator", name: "Days Until... Calculator", description: "Count the days until any event — with presets for common celebrations.", icon: "Clock", category: "Fun" },
  { slug: "numerology-calculator", name: "Numerology Calculator", description: "Find your Life Path, Expression, Soul Urge, and Personality numbers from birth date and name.", icon: "Sparkles", category: "Fun" },
  { slug: "chinese-zodiac-calculator", name: "Chinese Zodiac Calculator", description: "Find your Chinese zodiac animal and element from your birth year with traits and compatibility.", icon: "Stars", category: "Fun" },
  { slug: "dog-age-calculator", name: "Dog Age Calculator (in Human Years)", description: "Convert your dog's age to human years using the modern epigenetic formula and AVMA estimate.", icon: "Dog", category: "Fun" },
  { slug: "cat-age-calculator", name: "Cat Age Calculator (in Human Years)", description: "Convert your cat's age to human years using the AAFP / Cornell formula.", icon: "Cat", category: "Fun" },
  { slug: "birthday-paradox-calculator", name: "Birthday Paradox Calculator", description: "Compute the probability that 2 or more people in a group share a birthday.", icon: "Cake", category: "Fun" },
  { slug: "decision-wheel", name: "Decision Wheel (Spinner)", description: "Spin a randomized wheel to pick from your custom options with equal probability per option.", icon: "CircleDot", category: "Fun" },
  { slug: "magic-8-ball", name: "Magic 8-Ball", description: "Ask a yes/no question and get a classic Magic 8-Ball answer.", icon: "Sparkle", category: "Fun" },
  { slug: "coin-flip-dice-roller", name: "Coin Flip & Dice Roller", description: "Flip coins or roll dice with cryptographic randomness — single or bulk with full statistics.", icon: "Coins", category: "Fun" },

  // --- Gold & Silver ---
  { slug: "live-gold-rates", name: "Live Gold & Silver Rates", description: "Live international spot prices for gold (XAU/USD) and silver (XAG/USD), updated every 15 minutes.", icon: "Activity", category: "Gold & Silver" },
  { slug: "gold-price-calculator", name: "Gold Price Calculator", description: "Calculate gold value from weight and karat, or find how much gold you can buy for any amount.", icon: "Coins", category: "Gold & Silver" },
  { slug: "silver-price-calculator", name: "Silver Price Calculator", description: "Calculate silver value from weight and purity, or find how much silver you can buy for any amount.", icon: "Coins", category: "Gold & Silver" },
  { slug: "gold-silver-unit-converter", name: "Gold & Silver Weight Converter", description: "Convert between tola, masha, ratti, grams, and troy ounces for precious metals.", icon: "Ruler", category: "Gold & Silver" },
  { slug: "gold-purity-calculator", name: "Gold Purity & Impurity Calculator", description: "Find the pure gold and impurity content of any gold item based on weight and karat.", icon: "Percent", category: "Gold & Silver" },
  { slug: "karat-adjustment-calculator", name: "Karat Adjustment Calculator", description: "Calculate how much alloy or pure gold to add to convert gold from one karat to another.", icon: "Gem", category: "Gold & Silver" },
  { slug: "gold-silver-rate-finder", name: "Gold & Silver Rate Finder", description: "Reverse-calculate the effective rate per tola, gram, or ounce from money paid and weight received.", icon: "TrendingUp", category: "Gold & Silver" },
  { slug: "gold-weight-arithmetic-calculator", name: "Gold Weight Add / Subtract Calculator", description: "Add and subtract gold or silver weights across mixed units — grams, tola, ounce, and TMR.", icon: "Calculator", category: "Gold & Silver" },

  // --- Health ---
  { slug: "bmi-calculator", name: "BMI Calculator", description: "Calculate Body Mass Index and assess whether your weight is in a healthy range.", icon: "HeartPulse", category: "Health" },
  { slug: "bmr-calculator", name: "BMR Calculator", description: "Calculate your Basal Metabolic Rate — calories burned at rest.", icon: "Flame", category: "Health" },
  { slug: "tdee-calculator", name: "TDEE Calculator", description: "Calculate Total Daily Energy Expenditure for weight loss, maintenance, or gain.", icon: "Zap", category: "Health" },
  { slug: "ideal-weight-calculator", name: "Ideal Weight Calculator", description: "Find your ideal weight range using multiple validated medical formulas.", icon: "Scale", category: "Health" },
  { slug: "water-intake-calculator", name: "Water Intake Calculator", description: "Calculate your recommended daily water intake based on weight and exercise.", icon: "Droplets", category: "Health" },
  { slug: "body-fat-calculator", name: "Body Fat Calculator", description: "Estimate your body fat percentage using the US Navy measurement method.", icon: "Activity", category: "Health" },
  { slug: "macro-calculator", name: "Macro Calculator", description: "Calculate your daily protein, carbohydrate, and fat targets based on your goals.", icon: "PieChart", category: "Health" },
  { slug: "pregnancy-due-date-calculator", name: "Pregnancy Due Date Calculator", description: "Estimate your baby's due date based on your last menstrual period (LMP).", icon: "Baby", category: "Health" },
  { slug: "ovulation-calculator", name: "Ovulation Calculator", description: "Find your ovulation date and fertile window for conception planning.", icon: "Heart", category: "Health" },
  { slug: "heart-rate-zone-calculator", name: "Heart Rate Zone Calculator", description: "Calculate your max heart rate and five training zones for cardio workouts.", icon: "Activity", category: "Health" },
  { slug: "lean-body-mass-calculator", name: "Lean Body Mass Calculator", description: "Estimate your lean body mass and body fat using medical formulas.", icon: "User", category: "Health" },
  { slug: "waist-hip-ratio-calculator", name: "Waist-to-Hip Ratio Calculator", description: "Calculate waist-to-hip ratio — a strong predictor of cardiovascular risk.", icon: "Ruler", category: "Health" },
  { slug: "calories-burned-calculator", name: "Calories Burned Calculator", description: "Estimate calories burned for any activity using MET values and duration.", icon: "Target", category: "Health" },
  { slug: "heat-index-calculator", name: "Heat Index Calculator", description: "Find the 'feels like' temperature from air temperature and humidity.", icon: "Thermometer", category: "Health" },
  { slug: "sleep-cycle-calculator", name: "Sleep Cycle Calculator", description: "Find the best time to sleep or wake up based on 90-minute REM cycles.", icon: "Bed", category: "Health" },
  { slug: "pace-calculator", name: "Pace Calculator (Running)", description: "Convert finish time and pace per km/mile with predicted times for 5K, 10K, half, and full marathon.", icon: "Footprints", category: "Health" },
  { slug: "one-rep-max-calculator", name: "One-Rep Max (1RM) Calculator", description: "Estimate your true one-rep max from any sub-maximal set using six published formulas.", icon: "Dumbbell", category: "Health" },
  { slug: "blood-pressure-calculator", name: "Blood Pressure Category Checker", description: "Classify your blood pressure per ACC/AHA 2017 plus pulse pressure and MAP.", icon: "Heart", category: "Health" },
  { slug: "bsa-calculator", name: "Body Surface Area (BSA) Calculator", description: "Compute Body Surface Area in m² using 5 published formulas — used in chemotherapy dosing.", icon: "User", category: "Health" },
  { slug: "protein-intake-calculator", name: "Protein Intake Calculator", description: "Calculate daily protein needs for sedentary, active, fat-loss, muscle-gain, or athlete goals.", icon: "Beef", category: "Health" },
  { slug: "child-bmi-percentile-calculator", name: "Child BMI Percentile Calculator", description: "Find your child's BMI percentile per CDC growth charts (ages 2–20).", icon: "Baby", category: "Health" },
  { slug: "pregnancy-weight-gain-calculator", name: "Pregnancy Weight Gain Calculator", description: "Track recommended weight gain by week per IOM 2009 guidelines based on pre-pregnancy BMI.", icon: "Baby", category: "Health" },
  { slug: "bac-calculator", name: "Blood Alcohol Content (BAC) Calculator", description: "Estimate blood alcohol content from drinks consumed using the Widmark formula.", icon: "Wine", category: "Health" },
  { slug: "egfr-calculator", name: "eGFR Calculator (Kidney Function)", description: "Estimate Glomerular Filtration Rate using CKD-EPI 2021 with CKD stage classification.", icon: "Stethoscope", category: "Health" },
  { slug: "vo2-max-calculator", name: "VO₂ Max Calculator", description: "Estimate aerobic fitness from resting heart rate, 1-mile walk test, or 12-minute Cooper run.", icon: "Activity", category: "Health" },

  // --- Math ---
  { slug: "gpa-calculator", name: "GPA Calculator", description: "Calculate your Grade Point Average on the 4.0 scale from your courses.", icon: "GraduationCap", category: "Math" },
  { slug: "grade-calculator", name: "Grade Calculator", description: "Calculate your final grade from weighted categories like tests, homework, and exams.", icon: "BookOpen", category: "Math" },
  { slug: "student-result-card", name: "Student Result Card Calculator", description: "Subject-wise marks, grades, and a printable school result card for small schools and parents.", icon: "FileText", category: "Math" },
  { slug: "fraction-calculator", name: "Fraction Calculator", description: "Add, subtract, multiply, and divide fractions with automatic simplification.", icon: "Divide", category: "Math" },
  { slug: "ratio-calculator", name: "Ratio Calculator", description: "Simplify ratios and solve proportions with a missing value.", icon: "Scale", category: "Math" },
  { slug: "average-calculator", name: "Average Calculator", description: "Calculate mean, median, mode, range, and more from a data set.", icon: "BarChart3", category: "Math" },
  { slug: "lcm-gcd-calculator", name: "LCM / GCD Calculator", description: "Calculate Least Common Multiple and Greatest Common Divisor of integers.", icon: "Sigma", category: "Math" },
  { slug: "prime-checker", name: "Prime Number Checker", description: "Check if a number is prime and see its prime factorization.", icon: "Hash", category: "Math" },
  { slug: "scientific-calculator", name: "Scientific Calculator", description: "Evaluate mathematical expressions with trig, log, exponents, and constants.", icon: "Calculator", category: "Math" },
  { slug: "quadratic-solver", name: "Quadratic Equation Solver", description: "Solve ax² + bx + c = 0 with detailed root analysis.", icon: "SquareFunction", category: "Math" },
  { slug: "standard-deviation-calculator", name: "Standard Deviation Calculator", description: "Calculate mean, variance, and sample/population standard deviation.", icon: "BarChart3", category: "Math" },
  { slug: "permutation-combination-calculator", name: "Permutation & Combination Calculator", description: "Calculate nPr (arrangements) and nCr (selections) for combinatorial problems.", icon: "Shuffle", category: "Math" },
  { slug: "exponent-calculator", name: "Exponent / Power Calculator", description: "Calculate any base raised to any exponent (positive, negative, or decimal).", icon: "Superscript", category: "Math" },
  { slug: "square-root-calculator", name: "Square Root Calculator", description: "Calculate square root, cube root, square, and cube of any number.", icon: "Radical", category: "Math" },
  { slug: "logarithm-calculator", name: "Logarithm Calculator", description: "Calculate logarithms in any base, including common (log10), natural (ln), and binary (log2).", icon: "SquareFunction", category: "Math" },
  { slug: "triangle-solver", name: "Triangle Solver", description: "Solve any triangle from SSS, SAS, ASA, AAS, SSA, or right-triangle inputs with visualization.", icon: "Triangle", category: "Math" },
  { slug: "solid-volume-calculator", name: "3D Solid Volume Calculator", description: "Volume and surface area for sphere, cylinder, cone, cube, and rectangular prism.", icon: "Box", category: "Math" },
  { slug: "trigonometry-calculator", name: "Trigonometry Calculator", description: "Compute sin, cos, tan, csc, sec, cot for any angle with interactive unit-circle visualization.", icon: "Compass", category: "Math" },
  { slug: "distance-midpoint-calculator", name: "Distance & Midpoint Calculator", description: "Find the distance between two points, the midpoint, slope, and angle.", icon: "MapPin", category: "Math" },
  { slug: "statistics-batch-calculator", name: "Statistics Batch Calculator", description: "Mean, median, mode, std deviation, variance, quartiles for any list of numbers.", icon: "BarChart3", category: "Math" },
  { slug: "sequence-sums-calculator", name: "Arithmetic & Geometric Sequence Sums", description: "Compute the n-th term and sum of arithmetic or geometric sequences.", icon: "ListOrdered", category: "Math" },

  // --- Unit ---
  { slug: "weight-converter", name: "Weight Converter", description: "Convert between kilograms, pounds, grams, ounces, and stones.", icon: "Scale", category: "Unit" },
  { slug: "length-converter", name: "Length Converter", description: "Convert between meters, feet, kilometers, miles, inches and more.", icon: "Ruler", category: "Unit" },
  { slug: "temperature-converter", name: "Temperature Converter", description: "Convert between Celsius, Fahrenheit, and Kelvin instantly.", icon: "Thermometer", category: "Unit" },
  { slug: "area-converter-pk", name: "Area Converter (PK)", description: "Convert between Marla, Kanal, Square Feet, Square Meters, and Acres.", icon: "AreaChart", category: "Unit" },
  { slug: "volume-converter", name: "Volume Converter", description: "Convert between liters, gallons, cups, ml, fluid ounces, and more.", icon: "Beaker", category: "Unit" },
  { slug: "speed-converter", name: "Speed Converter", description: "Convert mph, km/h, m/s, knots, and feet per second.", icon: "Gauge", category: "Unit" },
  { slug: "time-unit-converter", name: "Time Converter", description: "Convert between seconds, minutes, hours, days, weeks, months, and years.", icon: "Clock", category: "Unit" },
  { slug: "data-storage-converter", name: "Data Storage Converter", description: "Convert between bytes, KB, MB, GB, TB, and PB using binary (1024) base.", icon: "HardDrive", category: "Unit" },
  { slug: "data-transfer-converter", name: "Data Transfer Rate Converter", description: "Convert bps, Kbps, Mbps, Gbps and MB/s, GB/s speeds.", icon: "Wifi", category: "Unit" },
  { slug: "energy-converter", name: "Energy Converter", description: "Convert joules, calories, kWh, BTU, and other energy units.", icon: "Zap", category: "Unit" },
  { slug: "power-converter", name: "Power Converter", description: "Convert watts, kilowatts, horsepower, and BTU/hr.", icon: "Power", category: "Unit" },
  { slug: "pressure-converter", name: "Pressure Converter", description: "Convert psi, bar, atm, pascal, kPa, and mmHg.", icon: "Activity", category: "Unit" },
  { slug: "angle-converter", name: "Angle Converter", description: "Convert between degrees, radians, and gradians.", icon: "Compass", category: "Unit" },
  { slug: "force-converter", name: "Force Converter", description: "Convert Newton, pound-force, kilogram-force, and dyne.", icon: "Magnet", category: "Unit" },
  { slug: "frequency-converter", name: "Frequency Converter", description: "Convert Hz, kHz, MHz, GHz, and revolutions per minute (RPM).", icon: "Radio", category: "Unit" },
  { slug: "torque-converter", name: "Torque Converter", description: "Convert Newton-meters, pound-feet, and kilogram-centimeters.", icon: "Cog", category: "Unit" },
  { slug: "density-converter", name: "Density Converter", description: "Convert kg/m³, g/cm³, lb/ft³, and other density units.", icon: "Weight", category: "Unit" },
  { slug: "wind-speed-converter", name: "Wind Speed Converter", description: "Convert km/h, mph, knots, m/s, and Beaufort with live wind speed for your country.", icon: "Wifi", category: "Unit" },
  { slug: "cooking-measurement-converter", name: "Cooking Measurement Converter", description: "Convert cups, tablespoons, ml, and grams for any ingredient with density adjustments.", icon: "ChefHat", category: "Unit" },

  // --- Utility ---
  { slug: "base-converter", name: "Base Converter", description: "Convert between binary, decimal, hexadecimal, and octal number systems.", icon: "Binary", category: "Utility" },
  { slug: "unix-timestamp-converter", name: "Unix Timestamp Converter", description: "Convert between Unix epoch timestamps and human-readable dates.", icon: "Clock", category: "Utility" },
  { slug: "color-converter", name: "Color Converter", description: "Convert between HEX, RGB, and HSL color formats with live preview.", icon: "Palette", category: "Utility" },
  { slug: "word-counter", name: "Word Counter", description: "Count words, characters, sentences, paragraphs, and estimate reading time.", icon: "FileText", category: "Utility" },
  { slug: "case-converter", name: "Case Converter", description: "Convert text between UPPERCASE, lowercase, Title Case, camelCase, and more.", icon: "Type", category: "Utility" },
  { slug: "password-generator", name: "Password Generator", description: "Generate strong random passwords with customizable length and character sets.", icon: "Key", category: "Utility" },
  { slug: "text-reverser", name: "Text Reverser / Palindrome Checker", description: "Reverse text by characters or words and check for palindromes.", icon: "RotateCcw", category: "Utility" },
  { slug: "qibla-direction-finder", name: "Qibla Direction Finder", description: "Find the exact direction of the Kaaba in Mecca from anywhere with compass and bearing.", icon: "Compass", category: "Islamic" },
  { slug: "qr-code-generator", name: "QR Code Generator", description: "Create QR codes from URLs, text, Wi-Fi, contacts, email, phone, SMS, and locations.", icon: "QrCode", category: "Utility" },
  { slug: "barcode-generator", name: "Barcode Generator", description: "Generate Code 128, EAN-13, UPC-A, Code 39, ITF-14, and more with PNG and SVG download.", icon: "Barcode", category: "Utility" },
  { slug: "regex-tester", name: "Regex Tester", description: "Test JavaScript regular expressions against sample text with live highlighting.", icon: "Search", category: "Utility" },
  { slug: "json-yaml-converter", name: "JSON ↔ YAML Converter", description: "Convert between JSON and YAML in either direction with live preview.", icon: "FileJson", category: "Utility" },
  { slug: "json-csv-converter", name: "JSON ↔ CSV Converter", description: "Convert JSON arrays of objects to CSV (or back) with custom delimiter and type coercion.", icon: "Database", category: "Utility" },
  { slug: "base64-converter", name: "Base64 Encode / Decode", description: "Encode text or files to Base64 (and back). UTF-8 safe and URL-safe variant supported.", icon: "Lock", category: "Utility" },
  { slug: "url-encoder", name: "URL Encoder / Decoder", description: "Percent-encode and decode URLs and query parameters with component and full-URI modes.", icon: "Link2", category: "Utility" },
  { slug: "hash-calculator", name: "Hash Calculator (MD5 / SHA-1 / SHA-256 / SHA-384 / SHA-512)", description: "Compute cryptographic hashes of text or files in your browser. No upload.", icon: "Hash", category: "Utility" },
  { slug: "uuid-generator", name: "UUID Generator (v4)", description: "Generate cryptographically random UUIDs (v4) in bulk with multiple format options.", icon: "Fingerprint", category: "Utility" },
  { slug: "markdown-converter", name: "Markdown ↔ HTML Converter", description: "Convert Markdown to HTML (or back) with live preview. Supports CommonMark and GFM.", icon: "FileTextIcon", category: "Utility" },
  { slug: "image-format-converter", name: "Image Format Converter (PNG / JPEG / WebP)", description: "Convert images between PNG, JPEG, and WebP in your browser with adjustable quality.", icon: "ImageIcon", category: "Utility" },
  { slug: "iban-validator", name: "IBAN Validator", description: "Validate International Bank Account Numbers via Mod-97 checksum with country detection.", icon: "BookOpen", category: "Utility" },
  { slug: "lorem-ipsum-generator", name: "Lorem Ipsum Generator", description: "Generate placeholder text — paragraphs, sentences, words, or specific byte counts.", icon: "Pilcrow", category: "Utility" },
];

// Total: 154 converters
