export type Unit = {
  name: string;
  symbol: string;
  toBase: number;
};

export const UNIT_CONFIGS: Record<string, Unit[]> = {
  "weight-converter": [
    { name: "Kilograms", symbol: "kg", toBase: 1 },
    { name: "Grams", symbol: "g", toBase: 0.001 },
    { name: "Pounds", symbol: "lb", toBase: 0.453592 },
    { name: "Ounces", symbol: "oz", toBase: 0.0283495 },
    { name: "Stones", symbol: "st", toBase: 6.35029 },
  ],
  "length-converter": [
    { name: "Kilometers", symbol: "km", toBase: 1000 },
    { name: "Meters", symbol: "m", toBase: 1 },
    { name: "Centimeters", symbol: "cm", toBase: 0.01 },
    { name: "Miles", symbol: "mi", toBase: 1609.34 },
    { name: "Yards", symbol: "yd", toBase: 0.9144 },
    { name: "Feet", symbol: "ft", toBase: 0.3048 },
    { name: "Inches", symbol: "in", toBase: 0.0254 },
  ],
  "area-converter-pk": [
    { name: "Kanal", symbol: "Kanal", toBase: 505.39232 },
    { name: "Marla", symbol: "Marla", toBase: 25.269616 },
    { name: "Square Feet", symbol: "sq ft", toBase: 0.092903 },
    { name: "Square Meters", symbol: "sq m", toBase: 1 },
    { name: "Acres", symbol: "Acre", toBase: 4046.86 },
  ],
  "volume-converter": [
    { name: "Liters", symbol: "L", toBase: 1 },
    { name: "Milliliters", symbol: "mL", toBase: 0.001 },
    { name: "US Gallons", symbol: "gal (US)", toBase: 3.78541 },
    { name: "UK Gallons", symbol: "gal (UK)", toBase: 4.54609 },
    { name: "US Cups", symbol: "cup", toBase: 0.236588 },
    { name: "US Fluid Ounces", symbol: "fl oz", toBase: 0.0295735 },
    { name: "Tablespoons", symbol: "tbsp", toBase: 0.0147868 },
    { name: "Teaspoons", symbol: "tsp", toBase: 0.00492892 },
    { name: "Cubic Meters", symbol: "m³", toBase: 1000 },
  ],
  "speed-converter": [
    { name: "Kilometers per hour", symbol: "km/h", toBase: 0.277778 },
    { name: "Miles per hour", symbol: "mph", toBase: 0.44704 },
    { name: "Meters per second", symbol: "m/s", toBase: 1 },
    { name: "Knots", symbol: "kn", toBase: 0.514444 },
    { name: "Feet per second", symbol: "ft/s", toBase: 0.3048 },
  ],
  "time-unit-converter": [
    { name: "Seconds", symbol: "sec", toBase: 1 },
    { name: "Minutes", symbol: "min", toBase: 60 },
    { name: "Hours", symbol: "hr", toBase: 3600 },
    { name: "Days", symbol: "day", toBase: 86400 },
    { name: "Weeks", symbol: "wk", toBase: 604800 },
    { name: "Months", symbol: "mo", toBase: 2629746 },
    { name: "Years", symbol: "yr", toBase: 31556952 },
  ],
  "data-storage-converter": [
    { name: "Bytes", symbol: "B", toBase: 1 },
    { name: "Kilobytes", symbol: "KB", toBase: 1024 },
    { name: "Megabytes", symbol: "MB", toBase: 1048576 },
    { name: "Gigabytes", symbol: "GB", toBase: 1073741824 },
    { name: "Terabytes", symbol: "TB", toBase: 1099511627776 },
    { name: "Petabytes", symbol: "PB", toBase: 1125899906842624 },
  ],
  "data-transfer-converter": [
    { name: "Bits per second", symbol: "bps", toBase: 1 },
    { name: "Kilobits per second", symbol: "Kbps", toBase: 1000 },
    { name: "Megabits per second", symbol: "Mbps", toBase: 1000000 },
    { name: "Gigabits per second", symbol: "Gbps", toBase: 1000000000 },
    { name: "Bytes per second", symbol: "B/s", toBase: 8 },
    { name: "Kilobytes per second", symbol: "KB/s", toBase: 8000 },
    { name: "Megabytes per second", symbol: "MB/s", toBase: 8000000 },
  ],
  "energy-converter": [
    { name: "Joules", symbol: "J", toBase: 1 },
    { name: "Kilojoules", symbol: "kJ", toBase: 1000 },
    { name: "Calories", symbol: "cal", toBase: 4.184 },
    { name: "Kilocalories", symbol: "kcal", toBase: 4184 },
    { name: "Kilowatt-hours", symbol: "kWh", toBase: 3600000 },
    { name: "British Thermal Units", symbol: "BTU", toBase: 1055.06 },
    { name: "Electron-volts", symbol: "eV", toBase: 1.60218e-19 },
  ],
  "power-converter": [
    { name: "Watts", symbol: "W", toBase: 1 },
    { name: "Kilowatts", symbol: "kW", toBase: 1000 },
    { name: "Megawatts", symbol: "MW", toBase: 1000000 },
    { name: "Horsepower (mechanical)", symbol: "hp", toBase: 745.7 },
    { name: "Horsepower (metric)", symbol: "PS", toBase: 735.5 },
    { name: "BTU per hour", symbol: "BTU/hr", toBase: 0.293071 },
  ],
  "pressure-converter": [
    { name: "Pascals", symbol: "Pa", toBase: 1 },
    { name: "Kilopascals", symbol: "kPa", toBase: 1000 },
    { name: "Bar", symbol: "bar", toBase: 100000 },
    { name: "Atmospheres", symbol: "atm", toBase: 101325 },
    { name: "PSI", symbol: "psi", toBase: 6894.76 },
    { name: "mmHg (Torr)", symbol: "mmHg", toBase: 133.322 },
  ],
  "force-converter": [
    { name: "Newtons", symbol: "N", toBase: 1 },
    { name: "Kilonewtons", symbol: "kN", toBase: 1000 },
    { name: "Pound-force", symbol: "lbf", toBase: 4.44822 },
    { name: "Kilogram-force", symbol: "kgf", toBase: 9.80665 },
    { name: "Dyne", symbol: "dyn", toBase: 0.00001 },
  ],
  "frequency-converter": [
    { name: "Hertz", symbol: "Hz", toBase: 1 },
    { name: "Kilohertz", symbol: "kHz", toBase: 1000 },
    { name: "Megahertz", symbol: "MHz", toBase: 1000000 },
    { name: "Gigahertz", symbol: "GHz", toBase: 1000000000 },
    { name: "Revolutions per minute", symbol: "rpm", toBase: 0.0166667 },
    { name: "Revolutions per second", symbol: "rps", toBase: 1 },
  ],
  "torque-converter": [
    { name: "Newton-meters", symbol: "N·m", toBase: 1 },
    { name: "Pound-feet", symbol: "lb·ft", toBase: 1.35582 },
    { name: "Pound-inches", symbol: "lb·in", toBase: 0.112985 },
    { name: "Kilogram-centimeters", symbol: "kg·cm", toBase: 0.0980665 },
    { name: "Kilogram-meters", symbol: "kg·m", toBase: 9.80665 },
  ],
  "density-converter": [
    { name: "Kilograms per cubic meter", symbol: "kg/m³", toBase: 1 },
    { name: "Grams per cubic centimeter", symbol: "g/cm³", toBase: 1000 },
    { name: "Grams per milliliter", symbol: "g/mL", toBase: 1000 },
    { name: "Pounds per cubic foot", symbol: "lb/ft³", toBase: 16.0185 },
    { name: "Pounds per gallon (US)", symbol: "lb/gal", toBase: 119.826 },
  ],
};
